### PR TITLE
Memcached

### PR DESCRIPTION
**Pull request by mcneelywv**

### CODE REVIEW

**Comment by druid628** [comment]
The setdata (line 158) method is all lower case does simple pie have a coding standard?

**Comment by mcneelywv** [comment]
They do but it's not PSR compliant by any stretch: http://simplepie.org/wiki/misc/coding_standards

**Comment by druid628** [comment]
:-/ :-1:

**Comment by druid628** [comment]
To keep it consistent with their terrible coding style, will you use set_data instead of setdata?

**Comment by mcneelywv** [comment]
Changed to camelCase.

**Pull request merged**
